export function buildRouteSummary(routeInfo, stops) {
  if (!routeInfo) return '';

  const { order, reordered, legs, totalDistance, totalDuration } = routeInfo;

  function formatDist(m) {
    return m >= 1000 ? `${(m / 1000).toFixed(1)} km` : `${Math.round(m)} m`;
  }
  function formatTime(s) {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    return h > 0 ? `${h}h ${m}m` : `${m} min`;
  }

  const lines = [];
  lines.push('OPTIMIZED DELIVERY ROUTE');
  lines.push('========================');
  lines.push(`Total distance : ${formatDist(totalDistance)}`);
  lines.push(`Estimated time : ${formatTime(totalDuration)}`);
  lines.push(`Stops          : ${stops.length}`);
  lines.push('');
  lines.push('STOP ORDER');
  lines.push('----------');

  order.slice(0, -1).forEach((si, pos) => {
    const s = reordered[si];
    const prefix = pos === 0 ? '[DEPOT] ' : `[${pos + 1}]     `;
    lines.push(`${prefix} ${s.label}`);
  });

  if (legs) {
    lines.push('');
    lines.push('LEG BREAKDOWN');
    lines.push('-------------');
    legs.forEach((leg, i) => {
      const from = reordered[order[i]];
      const to   = reordered[order[i + 1]];
      lines.push(`Leg ${i + 1}→${i + 2}: ${from.label.split(',')[0]} → ${to.label.split(',')[0]}`);
      lines.push(`         ${formatDist(leg.distance)} · ${formatTime(leg.duration)}`);
    });
  }

  lines.push('');
  lines.push(`Generated by Route Optimizer · ${new Date().toLocaleString()}`);
  return lines.join('\n');
}

export function downloadTxt(content, filename = 'route.txt') {
  const blob = new Blob([content], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text) {
  await navigator.clipboard.writeText(text);
}
